### ISSUE TITLE
Add App Summary page

### ISSUE THREAD

**Issue by witchpou** [starwit/lj-projectbuilder#141]
![image](https://user-images.githubusercontent.com/10485792/138935765-7fb6ea22-9f7d-4cb2-84ad-34f8f7a9df45.png)

**Comment by DerCed** [comment]
Information:
- Projectname
- Template
- Package Name
- Er-Diagram

**Comment by DerCed** [comment]
Information:
- Projectname
- Template
- Package Name
- Er-Diagram

**Comment by DerCed** [comment]
related to #154
