### ISSUE TITLE
Add function comments

### ISSUE THREAD

**Issue by DerCed** [starwit/lj-projectbuilder#151]
Add JsDoc comments to Frontend components

**Comment by sophiastr** [comment]
i want to deal with this issue.
I am interested in contributing to the project you are developing.
Do you still need help?

**Comment by witchpou** [comment]
Hi Sophia,

that's great. If you want we can schedule a meeting and we can tell you a little bit more about the project. We are building a new version on the v2 branch and definitly will be happy about help.

Best regards,
Anett
